### PR TITLE
Added colors and claiming

### PR DESCRIPTION
**Pull request by Exxarion**
I added new stuff to the plugin

- Claiming (With issues)
- Re-added colors
- A message displays when users try to break/place blocks in plots they do not own

### CODE REVIEW

**Comment by AndreyNazarchuk** [comment]
HORRAY WORK IS BEING DONE!!!

**Comment by wiez** [comment]
Awesome work have you done! Unfortunately I just rewrote the whole command handling system and merging this automatically will break everything D:
I'll try to merge it manually.

**Comment by Exxarion** [comment]
Oh okay, I will work from the update that you just pushed.

Im going to be adding helpers next :D

**Comment by wiez** [comment]
> Oh okay, I will work from the update that you just pushed.
> 
> Im going to be adding helpers next :D

Oh great, but try to add remove helpers if you want because I just finished add helpers :P

**Pull request closed without merging**
