### PR TITLE
Fixed permission

### PR DESCRIPTION
**Pull request by Jelly9912**

### CODE REVIEW

**Comment by iksaku** [comment]
:+1:

**Comment by Exxarion** [comment]
If that field is changed, it removes the /p command from all non-ops.

**Comment by Jelly9912** [comment]
What are you talking about?! You're wrong, cauze players still have e.g. myplot.command.auto permission and players can use this, i have like this on my server, cauze i edited this for op and now players can't make worlds but still can use other commands..

**Comment by Jelly9912** [comment]
Finally :v

**Pull request merged**
