### PR TITLE
makepublic and makeprivate subcommands

### PR DESCRIPTION
**Pull request by jasonwynn10**
Not sure if this is all I need to do...

### CODE REVIEW

**Comment by PEMapModder** [comment]
You one commit per file :/

**Comment by jasonwynn10** [comment]
didn't mean to add in the removal of the git files and the liscense

**Comment by Exxarion** [comment]
Why did you change the README file?

**Comment by jasonwynn10** [comment]
Most of these changes were because I hadn't originally intended to make a pull request of my additions and also that I don't know how to only make a request of specific commits.

**Comment by Aericio** [comment]
Why did you even remove the gitter.im from it?  You basically just removed everything and redid it without the html codes... With their gitter.im link removed.

**Comment by jasonwynn10** [comment]
I didn't originally Intend to make a pull request of the changes I made.

**Pull request closed without merging**
